import {
  Gift,
  Sparkles,
  Trophy,
  Tag,
  Coffee,
  UtensilsCrossed,
  Dumbbell,
  Cookie,
  ShoppingBag,
  BedDouble,
  Scissors,
  Car,
  Building2,
  Briefcase,
  Star,
  Heart,
  Droplet,
  Award,
  Crown,
  Pizza,
  IceCream,
  Wine,
  Beer,
  Croissant,
  CakeSlice,
  Flower,
  Flower2,
  Leaf,
  Sun,
  Moon,
  Zap,
  Flame,
  Diamond,
  Gem,
  BadgeCheck,
  Percent,
  Ticket,
  ShoppingCart,
  Store,
  Wrench,
  Stethoscope,
  Pill,
  Bike,
  Music,
  Camera,
  Palette,
  Phone,
  Mail,
  MapPin,
  Globe,
  AtSign,
  Share2,
  Clock,
  CheckCircle2,
  Smile,
  ThumbsUp,
  PawPrint,
  Fish,
  Bird,
  type LucideIcon,
} from "lucide-react";

export const iconRegistry: Record<string, LucideIcon> = {
  Gift, Sparkles, Trophy, Tag, Coffee, UtensilsCrossed, Dumbbell, Cookie,
  ShoppingBag, BedDouble, Scissors, Car, Building2, Briefcase, Star, Heart,
  Droplet, Award, Crown, Pizza, IceCream, Wine, Beer, Croissant, CakeSlice,
  Flower, Flower2, Leaf, Sun, Moon, Zap, Flame, Diamond, Gem, BadgeCheck,
  Percent, Ticket, ShoppingCart, Store, Wrench, Stethoscope, Pill, Bike,
  Music, Camera, Palette, Phone, Mail, MapPin, Globe, AtSign, Share2,
  Clock, CheckCircle2, Smile, ThumbsUp, PawPrint, Fish, Bird,
};

export const rewardIconOptions = [
  "Gift", "Sparkles", "Trophy", "Tag", "Award", "Crown", "Star", "Heart",
];

export const editorIconCategories: { label: string; icons: string[] }[] = [
  { label: "Restauration", icons: ["Coffee", "UtensilsCrossed", "Pizza", "IceCream", "Wine", "Beer", "Croissant", "CakeSlice", "Cookie", "Fish"] },
  { label: "Beauté & Bien-être", icons: ["Scissors", "Flower", "Flower2", "Sparkles", "Heart", "Sun", "Droplet", "Gem"] },
  { label: "Commerce", icons: ["ShoppingBag", "ShoppingCart", "Store", "Tag", "Percent", "Ticket", "Gift", "BadgeCheck"] },
  { label: "Récompenses", icons: ["Trophy", "Award", "Crown", "Star", "Diamond", "Zap", "Flame", "ThumbsUp"] },
  { label: "Services", icons: ["Car", "Wrench", "Stethoscope", "Pill", "Bike", "Dumbbell", "Music", "Camera"] },
  { label: "Contact", icons: ["Phone", "Mail", "MapPin", "Globe", "AtSign", "Share2", "Clock", "Smile"] },
  { label: "Animaux", icons: ["PawPrint", "Bird", "Fish", "Leaf"] },
];

export function getIcon(name: string): LucideIcon {
  return iconRegistry[name] ?? Gift;
}
